import Head from 'next/head'
import Image from 'next/image'
import BlockAboutUs from '../components/BlockAboutUs/BlockAboutUs'
import BlockPresentation from '../components/BlockPresentation/BlockPresentation'
import BlockViewed from '../components/BlockViewed/BlockViewed'
import BlockPopularCountry from '../components/BlockPopularCountry/BlockPopularCountry'
import BlockRecomendation from '../components/BlockRecomendation/BlockRecomendation'
import BlockAdvantage from '../components/BlockAdvantage/BlockAdvantage'
import BlockNewTour from '../components/BlockNewTour/BlockNewTour'
import BlockChangeCountry from '../components/BlockChangeCountry/BlockChangeCountry'
import BlockTypeTours from '../components/BlockTypeTours/BlockTypeTours'
import BlockRaitingTours from '../components/BlockRaitingTours/BlockRaitingTours'
import BlockTravelExperts from '../components/BlockTravelExperts/BlockTravelExperts'
import BlockSaleTours from '../components/BlockSaleTours/BlockSaleTours'
import BlockFeedback from '../components/BlockFeedback/BlockFeedback'
import BlockMoodTours from '../components/BlockMoodTours/BlockMoodTours'
import BlockFindTour from '../components/BlockFindTour/BlockFindTour'
import MainLayout from '../layouts/MainLayout'

export default function Home() {
  return (
    <MainLayout>
      <Head>
        <title>Traveler Market - Маркетплейс авторских туров</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* <BlockPresentation
        block_style='presentation_block'
      />
      <BlockViewed />
      <BlockPopularCountry />
      <BlockRecomendation />
      <BlockAdvantage />
      <BlockNewTour />
      <BlockChangeCountry />
      <BlockTypeTours />
      <BlockRaitingTours />
      <BlockTravelExperts />
      <BlockSaleTours />
      <BlockFeedback />
      <BlockMoodTours />
      <BlockFindTour /> */}
      <BlockAboutUs />
    </MainLayout>
  )
}
